export const ActionTypes = {
    SET_LIKE: 'SET_LIKE',
    REMOVE_LIKE: 'REMOVE_LIKE',
    GET_CHARACTER: 'GET_CHARACTER',
    GET_CHARACTERS_LIST: 'GET_CHARACTERS_LIST',
    GET_CHARACTER_EPISODES: 'GET_CHARACTER_EPISODES',
    GET_FAVORITE_CHARACTERS: 'GET_FAVORITE_CHARACTERS',
    SEARCH_BY_NAME: 'SEARCH_BY_NAME'
};
